In [2]:
! pip install numpy

In [2]:
import numpy as np
data=np.array([21,23,22,24])
print(data)
print(data[3])
print(type(data))
print(data.shape)

[21 23 22 24]
24
<class 'numpy.ndarray'>
(4,)


In [11]:
data=np.array([[21,22,23],[34,45,35],[67,68,69]])
print(data.shape)
print(data)
print(data[1,1])


(3, 3)
[[21 22 23]
 [34 45 35]
 [67 68 69]]
45


In [12]:
data=data=np.array([[[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69]]])
print(data.shape)
print(data.size)
print(data.ndim)


(1, 6, 3)
18
3


In [15]:
data=data=np.array([[[[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69],[21,22,23],[34,45,35],[67,68,69] ,[21,22,23],[34,45,35],[67,68,69]]]])
print(data.shape)
print(data.size)
print(data.ndim)

(1, 1, 12, 3)
36
4


In [2]:
import numpy as np
data=np.arange(0,10,2,dtype=int)
data

array([0, 2, 4, 6, 8])

In [12]:
data=np.arange(10,0,-2)
print(data)

[10  8  6  4  2]


In [11]:
data ,step=np.linspace(0,10,5,endpoint=False,retstep=True)
print(data)
print("step size:",step)

[0. 2. 4. 6. 8.]
step size: 2.0


In [10]:
data=np.logspace(1,10,4,base=10)
print(data)


[1.e+01 1.e+04 1.e+07 1.e+10]
